
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelTmp.BenhTmp;
import modelTmp.NguoiCachLyTmp;
import modelTmp.User;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin
 */
public class GiaoDien extends javax.swing.JFrame {

    List<NguoiCachLyTmp> listNCL = new ArrayList<>();
    List<BenhTmp> listBenh = new ArrayList<>();
    private XSSFWorkbook workbook;
    byte[] dataImg = null;

    /**
     * Creates new form GiaoDien
     */
    public GiaoDien(User userTmp) {
        initComponents();
        setLocationRelativeTo(null);
        //lbll_welcome.setText("Người đăng nhập : " + userTmp.getName() );
        //lbl_role.setText("Role: "+ userTmp.getRoler());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblResetPass = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSendMail = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlThongke = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlTracuu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlHuongdan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnlBenhan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlNcl = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlNhanvien = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        pnlXuatExcel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pnlNguoisd = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pnlRestore = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlTTUD = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled-2.png"))); // NOI18N

        lblResetPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/outline_account_circle_black_24dp.png"))); // NOI18N
        lblResetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetPassMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/outline_notifications_black_24dp.png"))); // NOI18N

        lblSendMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/outline_mark_chat_unread_black_24dp.png"))); // NOI18N
        lblSendMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSendMailMouseClicked(evt);
            }
        });

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CLOSE.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(247, 247, 247));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("TRA CỨU - BÁO CÁO");

        pnlThongke.setBackground(new java.awt.Color(232, 125, 158));
        pnlThongke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThongkeMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Thống kê");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/increase_100px_1.png"))); // NOI18N

        javax.swing.GroupLayout pnlThongkeLayout = new javax.swing.GroupLayout(pnlThongke);
        pnlThongke.setLayout(pnlThongkeLayout);
        pnlThongkeLayout.setHorizontalGroup(
            pnlThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        pnlThongkeLayout.setVerticalGroup(
            pnlThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongkeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        pnlTracuu.setBackground(new java.awt.Color(90, 200, 232));
        pnlTracuu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlTracuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTracuuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlTracuuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTracuuMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_100px_1.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tra cứu");

        javax.swing.GroupLayout pnlTracuuLayout = new javax.swing.GroupLayout(pnlTracuu);
        pnlTracuu.setLayout(pnlTracuuLayout);
        pnlTracuuLayout.setHorizontalGroup(
            pnlTracuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        pnlTracuuLayout.setVerticalGroup(
            pnlTracuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTracuuLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        pnlHuongdan.setBackground(new java.awt.Color(232, 190, 79));
        pnlHuongdan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlHuongdan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHuongdanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHuongdanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHuongdanMouseExited(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/book_100px_1.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Hướng dẫn");

        javax.swing.GroupLayout pnlHuongdanLayout = new javax.swing.GroupLayout(pnlHuongdan);
        pnlHuongdan.setLayout(pnlHuongdanLayout);
        pnlHuongdanLayout.setHorizontalGroup(
            pnlHuongdanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHuongdanLayout.setVerticalGroup(
            pnlHuongdanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHuongdanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pnlTracuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pnlThongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pnlHuongdan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlThongke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHuongdan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTracuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        jPanel6.setBackground(new java.awt.Color(247, 247, 247));

        jLabel13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("DANH MỤC");

        pnlBenhan.setBackground(new java.awt.Color(148, 114, 232));
        pnlBenhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlBenhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBenhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBenhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBenhanMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Bệnh án");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/form_100px.png"))); // NOI18N

        javax.swing.GroupLayout pnlBenhanLayout = new javax.swing.GroupLayout(pnlBenhan);
        pnlBenhan.setLayout(pnlBenhanLayout);
        pnlBenhanLayout.setHorizontalGroup(
            pnlBenhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );
        pnlBenhanLayout.setVerticalGroup(
            pnlBenhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBenhanLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        pnlNcl.setBackground(new java.awt.Color(232, 190, 79));
        pnlNcl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlNcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNclMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNclMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNclMouseExited(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/high_risk_100px.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Người cách li");

        javax.swing.GroupLayout pnlNclLayout = new javax.swing.GroupLayout(pnlNcl);
        pnlNcl.setLayout(pnlNclLayout);
        pnlNclLayout.setHorizontalGroup(
            pnlNclLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNclLayout.setVerticalGroup(
            pnlNclLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNclLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        pnlNhanvien.setBackground(new java.awt.Color(232, 125, 158));
        pnlNhanvien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNhanvienMouseExited(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_shield_100px.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Nhân viên");

        javax.swing.GroupLayout pnlNhanvienLayout = new javax.swing.GroupLayout(pnlNhanvien);
        pnlNhanvien.setLayout(pnlNhanvienLayout);
        pnlNhanvienLayout.setHorizontalGroup(
            pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNhanvienLayout.setVerticalGroup(
            pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanvienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(pnlNcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pnlBenhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBenhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNcl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(247, 247, 247));

        jLabel20.setBackground(new java.awt.Color(153, 153, 153));
        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("QUẢN TRỊ HỆ THỐNG");

        pnlXuatExcel.setBackground(new java.awt.Color(148, 114, 232));
        pnlXuatExcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlXuatExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlXuatExcelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlXuatExcelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlXuatExcelMouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Sitka Text", 1, 22)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Xuất file excel");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save_100px_1.png"))); // NOI18N

        javax.swing.GroupLayout pnlXuatExcelLayout = new javax.swing.GroupLayout(pnlXuatExcel);
        pnlXuatExcel.setLayout(pnlXuatExcelLayout);
        pnlXuatExcelLayout.setHorizontalGroup(
            pnlXuatExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlXuatExcelLayout.setVerticalGroup(
            pnlXuatExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlXuatExcelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlNguoisd.setBackground(new java.awt.Color(90, 200, 232));
        pnlNguoisd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlNguoisd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNguoisdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNguoisdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNguoisdMouseExited(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/engineer_100px_1.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Người sử dụng");

        javax.swing.GroupLayout pnlNguoisdLayout = new javax.swing.GroupLayout(pnlNguoisd);
        pnlNguoisd.setLayout(pnlNguoisdLayout);
        pnlNguoisdLayout.setHorizontalGroup(
            pnlNguoisdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNguoisdLayout.setVerticalGroup(
            pnlNguoisdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoisdLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24))
        );

        pnlRestore.setBackground(new java.awt.Color(232, 190, 79));
        pnlRestore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRestoreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlRestoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlRestoreMouseExited(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/data_recovery_100px_1.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Phục hồi dữ liệu");

        javax.swing.GroupLayout pnlRestoreLayout = new javax.swing.GroupLayout(pnlRestore);
        pnlRestore.setLayout(pnlRestoreLayout);
        pnlRestoreLayout.setHorizontalGroup(
            pnlRestoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRestoreLayout.setVerticalGroup(
            pnlRestoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestoreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26))
        );

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        pnlTTUD.setBackground(new java.awt.Color(232, 125, 158));
        pnlTTUD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        pnlTTUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTTUDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlTTUDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTTUDMouseExited(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/info_100px_1.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Thông tin phần mềm");

        javax.swing.GroupLayout pnlTTUDLayout = new javax.swing.GroupLayout(pnlTTUD);
        pnlTTUD.setLayout(pnlTTUDLayout);
        pnlTTUDLayout.setHorizontalGroup(
            pnlTTUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTTUDLayout.setVerticalGroup(
            pnlTTUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTUDLayout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(pnlXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlRestore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlNguoisd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTTUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pnlNguoisd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlTTUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlXuatExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRestore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel29.setBackground(new java.awt.Color(37, 149, 251));
        jLabel29.setFont(new java.awt.Font("Sitka Text", 1, 32)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("QUẢN LÝ NGƯỜI CÁCH LI TẠI TPHCM");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Phone-icon.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel31.setText("Phone : 1900 - 9095");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Communication-email-blue-icon.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel33.setText("Mail  : tokhaiyte@gmail.com");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/world-icon.png"))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel35.setText("Cài đặt ứng dụng Bluezone : http://www.bluezone.gov.vn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(885, Short.MAX_VALUE)
                        .addComponent(lblResetPass)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblSendMail)
                        .addGap(18, 18, 18)
                        .addComponent(lblExit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel31)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel33)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel35)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(130, 130, 130)
                                .addComponent(jLabel29)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblResetPass)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(lblSendMail)
                    .addComponent(lblExit))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void pnlTracuuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTracuuMouseEntered
        // TODO add your handling code here:
        pnlTracuu.setBackground(new java.awt.Color(0, 255, 204));
    }//GEN-LAST:event_pnlTracuuMouseEntered

    private void pnlTracuuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTracuuMouseExited
        // TODO add your handling code here:
        pnlTracuu.setBackground(new java.awt.Color(90, 200, 232));
    }//GEN-LAST:event_pnlTracuuMouseExited

    private void pnlThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongkeMouseEntered
        // TODO add your handling code here:
        pnlThongke.setBackground(new java.awt.Color(255, 0, 153));
    }//GEN-LAST:event_pnlThongkeMouseEntered

    private void pnlThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongkeMouseExited
        // TODO add your handling code here:
        pnlThongke.setBackground(new java.awt.Color(232, 125, 158));
    }//GEN-LAST:event_pnlThongkeMouseExited

    private void pnlHuongdanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuongdanMouseEntered
        // TODO add your handling code here:
        pnlHuongdan.setBackground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_pnlHuongdanMouseEntered

    private void pnlHuongdanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuongdanMouseExited
        // TODO add your handling code here:
        pnlHuongdan.setBackground(new java.awt.Color(232, 190, 79));
    }//GEN-LAST:event_pnlHuongdanMouseExited

    private void pnlNclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNclMouseEntered
        // TODO add your handling code here:
        pnlNcl.setBackground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_pnlNclMouseEntered

    private void pnlNclMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNclMouseExited
        // TODO add your handling code here:
        pnlNcl.setBackground(new java.awt.Color(232, 190, 79));
    }//GEN-LAST:event_pnlNclMouseExited

    private void pnlBenhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBenhanMouseEntered
        // TODO add your handling code here:
        pnlBenhan.setBackground(new java.awt.Color(204, 51, 255));
    }//GEN-LAST:event_pnlBenhanMouseEntered

    private void pnlBenhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBenhanMouseExited
        // TODO add your handling code here:
        pnlBenhan.setBackground(new java.awt.Color(148, 114, 232));
    }//GEN-LAST:event_pnlBenhanMouseExited

    private void pnlNhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanvienMouseEntered
        // TODO add your handling code here:
        pnlNhanvien.setBackground(new java.awt.Color(255, 0, 153));
    }//GEN-LAST:event_pnlNhanvienMouseEntered

    private void pnlNhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanvienMouseExited
        // TODO add your handling code here:
        pnlNhanvien.setBackground(new java.awt.Color(232, 125, 158));
    }//GEN-LAST:event_pnlNhanvienMouseExited

    private void pnlNguoisdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoisdMouseEntered
        // TODO add your handling code here:
        pnlNguoisd.setBackground(new java.awt.Color(0, 255, 204));
    }//GEN-LAST:event_pnlNguoisdMouseEntered

    private void pnlNguoisdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoisdMouseExited
        // TODO add your handling code here:
        pnlNguoisd.setBackground(new java.awt.Color(90, 200, 232));
    }//GEN-LAST:event_pnlNguoisdMouseExited

    private void pnlTTUDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTTUDMouseEntered
        // TODO add your handling code here:
        pnlTTUD.setBackground(new java.awt.Color(255, 0, 153));
    }//GEN-LAST:event_pnlTTUDMouseEntered

    private void pnlTTUDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTTUDMouseExited
        // TODO add your handling code here:
        pnlTTUD.setBackground(new java.awt.Color(232, 125, 158));
    }//GEN-LAST:event_pnlTTUDMouseExited

    private void pnlXuatExcelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXuatExcelMouseEntered
        // TODO add your handling code here:
        pnlXuatExcel.setBackground(new java.awt.Color(204, 51, 255));
    }//GEN-LAST:event_pnlXuatExcelMouseEntered

    private void pnlXuatExcelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXuatExcelMouseExited
        // TODO add your handling code here:
        pnlXuatExcel.setBackground(new java.awt.Color(148, 114, 232));
    }//GEN-LAST:event_pnlXuatExcelMouseExited

    private void pnlRestoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRestoreMouseEntered
        // TODO add your handling code here:
        pnlRestore.setBackground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_pnlRestoreMouseEntered

    private void pnlRestoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRestoreMouseExited
        // TODO add your handling code here:
        pnlRestore.setBackground(new java.awt.Color(232, 190, 79));
    }//GEN-LAST:event_pnlRestoreMouseExited

    private void lblResetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetPassMouseClicked
        // TODO add your handling code here:
        DoiPass dp = new DoiPass(main.userTmp);
        dp.setVisible(true);
    }//GEN-LAST:event_lblResetPassMouseClicked

    private void pnlNclMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNclMouseClicked
        // TODO add your handling code here:
        NguoiCachLy ncl = new NguoiCachLy(main.userTmp);
        ncl.setVisible(true);
        dispose();

    }//GEN-LAST:event_pnlNclMouseClicked

    private void pnlBenhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBenhanMouseClicked
        // TODO add your handling code here:
        BenhAn ba = new BenhAn(main.userTmp);
        ba.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnlBenhanMouseClicked

    private void pnlNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanvienMouseClicked
        // TODO add your handling code here:
        if (main.userTmp.getRoler().equals("admin")) {
            NhanVien nv = new NhanVien();
            nv.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Chức năng chỉ dành cho Người quản trị.");
        }
    }//GEN-LAST:event_pnlNhanvienMouseClicked

    private void pnlThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongkeMouseClicked
        // TODO add your handling code here:
        main.tk.setVisible(true);
    }//GEN-LAST:event_pnlThongkeMouseClicked

    private void pnlXuatExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXuatExcelMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Save as");
        FileNameExtensionFilter f = new FileNameExtensionFilter("xls", "xlsx");
        FileOutputStream out = null;
        chooser.setFileFilter(f);
        int excel = chooser.showSaveDialog(null);
        if (excel == JFileChooser.APPROVE_OPTION) {
            listNCL.clear();
            listBenh.clear();
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection(main.url, main.user, main.pass);
                String sql = "select * from NguoiCachLi where hide = 0";
                java.sql.Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    NguoiCachLyTmp ncl = new NguoiCachLyTmp();
                    ncl.setMacl(rs.getString(1));
                    ncl.setTen(rs.getString(2));
                    ncl.setGt(rs.getBoolean("GioiTinh") == true ? "Nam" : "Nữ");
                    ncl.setNs(rs.getString(4));
                    ncl.setSdt(rs.getString(5));
                    ncl.setDc(rs.getString(6));
                    ncl.setNcl(rs.getString(7));
                    ncl.setDien(rs.getString(8));
                    ncl.setTx(rs.getString(9));
                    listNCL.add(ncl);
                }

                sql = "select * from benh where hide = 0";
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    BenhTmp benh = new BenhTmp();
                    benh.setMcl(rs.getString(1));
                    benh.setNgay(rs.getString(2));
                    benh.setDien(rs.getString(3));
                    benh.setBh(rs.getString(4));
                    benh.setGc(rs.getString(5));
                    listBenh.add(benh);
                }

                con.close();
                rs.close();
            } catch (Exception e) {
                System.out.println(e);
            }
            try {
                workbook = new XSSFWorkbook();
                XSSFSheet spreadsheet1 = workbook.createSheet("Người cách ly");
                XSSFRow rows1 = null, rows2 = null;
                Cell cells1 = null, cells2 = null;
                CellStyle cs = headerCellStyle();
                CellStyle csc = coCellStyle();
                rows1 = spreadsheet1.createRow((short) 3);
                rows1.setHeight((short) 700);
                cells1 = rows1.createCell(0, CellType.STRING);
                cells1.setCellValue("Mã Cách ly");
                cells1.setCellStyle(cs);
                cells1 = rows1.createCell(1, CellType.STRING);
                cells1.setCellValue("Họ và tên");
                cells1.setCellStyle(cs);
                cells1 = rows1.createCell(2, CellType.STRING);
                cells1.setCellValue("Giới tính");
                cells1.setCellStyle(cs);
                cells1 = rows1.createCell(3, CellType.STRING);
                cells1.setCellValue("Ngày sinh");
                cells1.setCellStyle(cs);
                cells1 = rows1.createCell(4, CellType.STRING);
                cells1.setCellValue("Số điện thoại");
                cells1.setCellStyle(cs);
                cells1 = rows1.createCell(5, CellType.STRING);
                cells1.setCellValue("Địa chỉ");
                cells1.setCellStyle(cs);
                cells1 = rows1.createCell(6, CellType.STRING);
                cells1.setCellValue("Ngày cách ly");
                cells1.setCellStyle(cs);
                cells1 = rows1.createCell(7, CellType.STRING);
                cells1.setCellValue("Diện");
                cells1.setCellStyle(cs);
                cells1 = rows1.createCell(8, CellType.STRING);
                cells1.setCellValue("Tiếp xúc");
                cells1.setCellStyle(cs);
                for (int i = 0; i < listNCL.size(); i++) {
                    NguoiCachLyTmp ncl = listNCL.get(i);
                    rows1 = spreadsheet1.createRow((short) 4 + i);
                    rows1.setHeight((short) 500);
                    cells1 = rows1.createCell(0);
                    cells1.setCellValue(ncl.getMacl());
                    cells1.setCellStyle(csc);
                    cells1 = rows1.createCell(1);
                    cells1.setCellValue(ncl.getTen());
                    cells1.setCellStyle(csc);
                    cells1 = rows1.createCell(2);
                    cells1.setCellValue(ncl.getGt());
                    cells1.setCellStyle(csc);
                    cells1 = rows1.createCell(3);
                    cells1.setCellValue(ncl.getNs().toString());
                    cells1.setCellStyle(csc);
                    cells1 = rows1.createCell(4);
                    cells1.setCellValue(ncl.getSdt());
                    cells1.setCellStyle(csc);
                    cells1 = rows1.createCell(5);
                    cells1.setCellValue(ncl.getDc());
                    cells1.setCellStyle(csc);
                    cells1 = rows1.createCell(6);
                    cells1.setCellValue(ncl.getNcl());
                    cells1.setCellStyle(csc);
                    cells1 = rows1.createCell(7);
                    cells1.setCellValue(ncl.getDien());
                    cells1.setCellStyle(csc);
                    cells1 = rows1.createCell(8);
                    cells1.setCellValue(ncl.getTx());
                    cells1.setCellStyle(csc);
                }

                XSSFSheet spreadsheet2 = workbook.createSheet("Bệnh án");
                rows2 = spreadsheet2.createRow((short) 3);
                rows2.setHeight((short) 700);
                cells2 = rows2.createCell(0, CellType.STRING);
                cells2.setCellValue("Mã Cách ly");
                cells2.setCellStyle(cs);
                cells2 = rows2.createCell(1, CellType.STRING);
                cells2.setCellValue("Ngày");
                cells2.setCellStyle(cs);
                cells2 = rows2.createCell(2, CellType.STRING);
                cells2.setCellValue("Diện");
                cells2.setCellStyle(cs);
                cells2 = rows2.createCell(3, CellType.STRING);
                cells2.setCellValue("Biểu hiện");
                cells2.setCellStyle(cs);
                cells2 = rows2.createCell(4, CellType.STRING);
                cells2.setCellValue("Ghi chú");
                cells2.setCellStyle(cs);
                for (int i = 0; i < listBenh.size(); i++) {
                    BenhTmp benh = listBenh.get(i);
                    rows2 = spreadsheet2.createRow((short) 4 + i);
                    rows2.setHeight((short) 500);
                    cells2 = rows2.createCell(0);
                    cells2.setCellValue(benh.getMcl());
                    cells2.setCellStyle(csc);
                    cells2 = rows2.createCell(1);
                    cells2.setCellValue(benh.getNgay());
                    cells2.setCellStyle(csc);
                    cells2 = rows2.createCell(2);
                    cells2.setCellValue(benh.getDien());
                    cells2.setCellStyle(csc);
                    cells2 = rows2.createCell(3);
                    cells2.setCellValue(benh.getBh());
                    cells2.setCellStyle(csc);
                    cells2 = rows2.createCell(4);
                    cells2.setCellValue(benh.getGc());
                    cells2.setCellStyle(csc);
                }

                for (int i = 0; i < 9; i++) {
                    spreadsheet1.autoSizeColumn(i);
                }
                for (int i = 0; i < 5; i++) {
                    spreadsheet2.autoSizeColumn(i);
                }

                out = new FileOutputStream(chooser.getSelectedFile() + ".xlsx");
                workbook.write(out);
                out.close();
                JOptionPane.showMessageDialog(null, "Export file excel thành công");
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ổ đĩa");
        }
    }//GEN-LAST:event_pnlXuatExcelMouseClicked

    private void pnlRestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRestoreMouseClicked
        // TODO add your handling code here:
        if (main.userTmp.getRoler().equals("admin")) {
            Restore rs = new Restore();
            rs.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Chức năng chỉ dành cho Người quản trị.");
        }
    }//GEN-LAST:event_pnlRestoreMouseClicked

    private void lblSendMailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSendMailMouseClicked
        // TODO add your handling code here:
        if (main.userTmp.getRoler().equals("admin")) {
            Mail send = new Mail();
            send.setVisible(true);
        } else {
            JOptionPane.showConfirmDialog(this, "Chức năng chỉ dành cho Người quản trị");
        }
    }//GEN-LAST:event_lblSendMailMouseClicked

    private void pnlNguoisdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoisdMouseClicked
        // TODO add your handling code here:
        Nguoisd nsd = new Nguoisd(main.userTmp);
        nsd.setVisible(true);
    }//GEN-LAST:event_pnlNguoisdMouseClicked

    private void pnlTTUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTTUDMouseClicked
        // TODO add your handling code here:
        TTUP ttup = new TTUP();
        ttup.setVisible(true);
    }//GEN-LAST:event_pnlTTUDMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        HuongDanHD hd = new HuongDanHD();
        hd.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void pnlHuongdanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuongdanMouseClicked
        // TODO add your handling code here:
        HuongDanHD hd = new HuongDanHD();
        hd.setVisible(true);
    }//GEN-LAST:event_pnlHuongdanMouseClicked

    private void pnlTracuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTracuuMouseClicked
        // TODO add your handling code here:
        NguoiCachLy ncl = new NguoiCachLy(main.userTmp);
        ncl.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnlTracuuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main.userTmp.setName("admin");
                main.userTmp.setRoler("admin");
                new GiaoDien(main.userTmp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblResetPass;
    private javax.swing.JLabel lblSendMail;
    private javax.swing.JPanel pnlBenhan;
    private javax.swing.JPanel pnlHuongdan;
    private javax.swing.JPanel pnlNcl;
    private javax.swing.JPanel pnlNguoisd;
    private javax.swing.JPanel pnlNhanvien;
    private javax.swing.JPanel pnlRestore;
    private javax.swing.JPanel pnlTTUD;
    private javax.swing.JPanel pnlThongke;
    private javax.swing.JPanel pnlTracuu;
    private javax.swing.JPanel pnlXuatExcel;
    // End of variables declaration//GEN-END:variables
    private CellStyle headerCellStyle() {
        CellStyle cellStyle = workbook.createCellStyle();
        cellStyle.setAlignment(HorizontalAlignment.CENTER);
        cellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
        cellStyle.setBorderBottom(BorderStyle.THICK);
        cellStyle.setBorderLeft(BorderStyle.THICK);
        cellStyle.setBorderRight(BorderStyle.THICK);
        cellStyle.setBorderTop(BorderStyle.THICK);

        Font font = workbook.createFont();
        font.setBold(true);
        font.setFontName("Times New Roman");
        font.setFontHeight((short) 350);
        cellStyle.setFont(font);
        return cellStyle;
    }

    private CellStyle coCellStyle() {
        CellStyle cellStyle = workbook.createCellStyle();
        cellStyle.setAlignment(HorizontalAlignment.CENTER);
        cellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
        cellStyle.setBorderBottom(BorderStyle.THIN);
        cellStyle.setBorderLeft(BorderStyle.THICK);
        cellStyle.setBorderRight(BorderStyle.THICK);
        cellStyle.setBorderTop(BorderStyle.THIN);

        Font font = workbook.createFont();
        font.setFontName("Times New Roman");
        font.setFontHeight((short) 250);
        cellStyle.setFont(font);
        return cellStyle;
    }
}
